version: "3.7"

services:
    # image project
    app:
        container_name: devpay-app
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: tifabio/devpay-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - devpaynetwork
    
    # nginx
    nginx:
        container_name: devpay-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8080:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - devpaynetwork

    # db mysql
    mysql:
        container_name: devpay-mysql
        image: mysql:5.7.39
        
        restart: unless-stopped
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks: 
            - devpaynetwork

networks: 
    devpaynetwork:
        driver: bridge